# Generated by Django 3.0.4 on 2020-05-30 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='clinics',
            options={'verbose_name_plural': 'Clinics'},
        ),
        migrations.AlterModelOptions(
            name='helprequests',
            options={'verbose_name_plural': 'HelpRequests'},
        ),
        migrations.AlterModelOptions(
            name='helprequestsdetail',
            options={'verbose_name_plural': 'HelpRequestsDetail'},
        ),
        migrations.AlterModelOptions(
            name='helpresponces',
            options={'verbose_name_plural': 'HelpResponces'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AddField(
            model_name='helprequestsdetail',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='helprequests',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='helprequestsdetail',
            name='clinics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='VUD.Clinics'),
        ),
        migrations.AlterField(
            model_name='helprequestsdetail',
            name='postid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='VUD.HelpRequests'),
        ),
        migrations.AlterField(
            model_name='helpresponces',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
